# Constructing Basic Shapes in OpenCV#


In [1]:
import cv2
import constant as ct
import jupytercv as jp
import numpy as np

(228, 230, 7)
(125, 125, 125)


Criando uma imagem de background para ilustrar o uso das cores

In [2]:
image = np.zeros((400,400,3), dtype='uint8')
image[:] = ct.GRAY

#cv2.imshow("Tela", image)
#cv2.waitKey(1000)

Desenhando linhas com `cv2.line()`

`img = line(img, pt1, pt2, color, thickness=1, lineType=8, shift=0)`

In [3]:
cv2.line(image, (200,0), (400,400), ct.RED, 3)
cv2.line(image, (200,0), (0,400), ct.RED, 3)
cv2.line(image, (0,400), (400,400), ct.RED, 3)
cv2.line(image, (200,0), (200,400), ct.BLACK, 3)
cv2.imshow('linhas', image)
cv2.waitKey(0)

3

Desenhando retângulos

`img = rectangle(img, pt1, pt2, color, thickness=1, lineType=8, shift=0)`

In [3]:
image = np.zeros((400,400,3), dtype='uint8')
image[:] = ct.GRAY

cv2.rectangle(image, (10, 50), (60, 300), ct.GREEN, 3)
cv2.rectangle(image, (80, 50), (130, 300), ct.BLUE, -1)
cv2.rectangle(image, (150, 50), (350, 100), ct.RED, -1) # O negativo desenha sólidos
cv2.rectangle(image, (150, 150), (350, 300), ct.CYAN, 10)

cv2.imshow('Retangulos', image)
cv2.waitKey(0)

13

Desenhando círculos

`img = circle(img, center, radius, color, thickness=1, lineType=8, shift=0)`


In [3]:
image = np.zeros((400,400,3), dtype='uint8')
image[:] = ct.GRAY

cv2.circle(image, (50, 50), 20, ct.GREEN, 3)
cv2.circle(image, (100, 100), 30, ct.BLUE, -1)
cv2.circle(image, (200, 200), 40, ct.MAGENTA, 10)
cv2.circle(image, (300, 300), 40, ct.CYAN, -1)

cv2.imshow('Circulos', image)
cv2.waitKey(0)


13

## Formas avançadas ##


In [3]:
image = np.zeros((300,300,3), dtype='uint8')
image[:] = ct.LIGHT_GRAY

Clip Line

`retval, pt1, pt2 = clipLine(imgRect, pt1, pt2)

In [4]:
cv2.line(image, (0, 0), (300, 300), ct.GREEN, 3)
cv2.rectangle(image, (0, 0), (100, 100), ct.BLUE, 3)
ret, p1, p2 = cv2.clipLine((0, 0, 100, 100), (0, 0), (300, 300))

if ret:
    cv2.line(image, p1, p2, ct.YELLOW, 3)

cv2.imshow('clipline', image)
cv2.waitKey(0)

13

Setas

`cv.arrowedLine(img, pt1, pt2, color, thickness=1, lineType=8, shift=0, tipLength=0.1)`

In [2]:
image = np.zeros((300,300,3), dtype='uint8')
image[:] = ct.LIGHT_GRAY

cv2.arrowedLine(image, (50, 50), (200, 50), ct.RED, 3, 8, 0, 0.1)
cv2.arrowedLine(image, (50, 120), (200, 120), ct.GREEN, 3, cv2.LINE_AA, 0, 0.3)
cv2.arrowedLine(image, (50, 200), (200, 200), ct.BLUE, 3, 8, 0, 0.3)

cv2.imshow('setas', image)
cv2.waitKey(0)

13

Elipses

`cv2.ellipse(img, center, axes, angle, startAngle, endAngle, color, thickness=1, lineType=8, shift=0)`

In [ ]:
image = np.zeros((300,300,3), dtype='uint8')
image[:] = ct.LIGHT_GRAY

cv2.ellipse(image, (80, 80), (60, 40), 0, 0, 360, ct.RED, -1)
cv2.ellipse(image, (80, 200), (80, 180), 0, 0, 360, ct.GREEN, 3)
cv2.ellipse(image, (80, 200), (10, 40), 0, 0, 360, ct.BLUE, 3)
cv2.ellipse(image, (200, 200), (10, 40), 0, 0, 180, ct.YELLOW, 3)
cv2.ellipse(image, (200, 100), (10, 40), 0, 0, 270, ct.CYAN, 3)
#cv2.ellipse(image, (250, 250), (30, 30), 0, 0, 360, ct.RAND, 3)
cv2.ellipse(image, (250, 100), (20, 40), 45, 0, 360, ct.MAGENTA, 3)

cv2.imshow('Elipses', image)
cv2.waitKey(0)

Polígonos

`cv2.polylines(img, pts, isClosed, color, thickness=1, lineType=8, shift=0)`

In [5]:
image = np.zeros((300,300,3), dtype='uint8')
image[:] = ct.LIGHT_GRAY

# These points define a triangle
pts = np.array([[250, 5], [220, 80], [280, 80]], np.int32)
print(pts)
# Reshape to shape (number_vertex, 1, 2)
pts = pts.reshape((-1, 1, 2))
print(pts)
# Print the shapes: this line is not necessary, only for visualization
print("shape of pts '{}'".format(pts.shape))
# this gives: shape of pts '(3, 1, 2)'

cv2.polylines(image, [pts], isClosed=True, color=ct.GREEN, thickness=3, lineType=8, shift=0)

cv2.imshow('polígonos', image)
cv2.waitKey(0)


[[250   5]
 [220  80]
 [280  80]]
[[[250   5]]

 [[220  80]]

 [[280  80]]]
shape of pts '(3, 1, 2)'


13

## Eventos do mouse com OpenCV ##

cv2.setMouseCallback(windowName, onMouse, param=None)

In [2]:
'''
def eventMouseFunc(event, x, y, flags, param):
    if event == cv2.EVENT_RBUTTONDBLCLK:
        print("{] e {}".format(x, y))
'''


starwars = cv2.imread('starwars.jpg')

cv2.imshow("starwars", starwars)
#cv2.setMouseCallback('starwars', eventMouseFunc)
cv2.waitKey(0)
